services:
  app:
    build:
      context: ./docker/php
      args:
        PUID: ${PUID:-1000}
        PGID: ${PGID:-1000}
    container_name: backend-app
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/zz-custom.ini:ro
    environment:
      APP_ENV: local
    depends_on:
      - db
      - redis
    networks:
      - backend

  web:
    image: nginx:1.25-alpine
    container_name: backend-web
    depends_on:
      - app
    ports:
      - "${HTTP_PORT:-8080}:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - backend
  
  frontend:
    build:
      context: ./
      dockerfile: ./docker/frontend/Dockerfile
    container_name: frontend-vue
    working_dir: /app
    environment:
      - VUE_APP_API_BASE=http://localhost:8080/api
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "${FRONTEND_PORT:-8081}:8080"
    depends_on:
      - web
    networks:
      - backend

  db:
    image: postgres:14-alpine
    container_name: backend-db
    environment:
      POSTGRES_DB: ${DB_DATABASE:-backend}
      POSTGRES_USER: ${DB_USERNAME:-backend}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7-alpine
    container_name: backend-redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend

  composer:
    image: composer:2
    container_name: backend-composer
    user: "${PUID:-1000}:${PGID:-1000}"
    working_dir: /var/www/html
    environment:
      COMPOSER_CACHE_DIR: /tmp/composer-cache
    volumes:
      - ./backend:/var/www/html
      - ./composer-cache:/tmp/composer-cache
    entrypoint: ["composer", "--ansi", "--no-interaction"]
    networks:
      - backend

  artisan:
    build:
      context: ./docker/php
      args:
        PUID: ${PUID:-1000}
        PGID: ${PGID:-1000}
    container_name: backend-artisan
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
      - redis
    entrypoint: ["php", "/var/www/html/artisan"]
    networks:
      - backend

volumes:
  db_data:
  redis_data:

networks:
  backend:
    driver: bridge
